### ISSUE TITLE
The list project could use a modernisation of style

### ISSUE THREAD

**Issue by brickviking** [brickviking/list#5]
# Style
Simply put, I created this project when I didn't really know what good style was. I've since learned that many different projects and environments have their own respective rules for how to manage style, and indeed there have been quasi-religious wars over style.

I want to choose a style that sort of fits, but some of the things I need to do involve reformatting so that there are no tabs except where absolutely necessary (for example, in output strings) in any of the source files. This isn't going to be a small project, and will involve quite a few different facets. Here's a quick list of the things I need to do:

###[tasklist]
- [ ] #6 Replace tabs with spaces, we're not starving for disk space any more.
- [ ] #7 Replace a=b with a = b throughout, including int ptr = *thingToPointTo.
- [ ] #8 I went with personal of func name(vartype var) {, this should go throughout.
- [ ] #9 Consolidate comments. There's too many.
- [ ] Add things here as I need.

Hopefully many of these things will get worked on over the next month or ten.
